"""admin_message — owner/manager "Contact admin" inbox.

Creates `admin_message`: a message a signed-in owner or manager sends to the
platform admins (question, problem, feature request), with an optional
related location, and a tiny `open` -> `resolved` triage lifecycle admins
work from `GET /admin/messages` / `PATCH /admin/messages/{id}`.

`related_location_id` is `ON DELETE SET NULL`: the message outlives the
location it mentions. Sender identity (`sender_cognito_sub`, `sender_role`,
`sender_email`, `sender_name`) is a snapshot taken at send time from the
verified token + local profile, so the inbox stays readable even if the
account is later deleted. Two indexes: `(status, created_at)` for the admin
queue and `(sender_cognito_sub, created_at)` for the per-sender rolling-hour
rate limit.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Revision id kept short
(`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0017_admin_message
Revises: 0016_location_cuisine
Create Date: 2026-10-07
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017_admin_message"
down_revision: Union[str, None] = "0016_location_cuisine"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "admin_message",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("sender_cognito_sub", sa.String(length=64), nullable=False),
        sa.Column("sender_role", sa.String(length=16), nullable=False),
        sa.Column("sender_email", sa.String(length=254), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("related_location_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_location_id"], ["restaurant_location.id"], ondelete="SET NULL"
        ),
    )
    op.create_index("ix_admin_message_status_created", "admin_message", ["status", "created_at"])
    op.create_index(
        "ix_admin_message_sender_created",
        "admin_message",
        ["sender_cognito_sub", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_admin_message_sender_created", table_name="admin_message")
    op.drop_index("ix_admin_message_status_created", table_name="admin_message")
    op.drop_table("admin_message")
