"""listing_report — new table for public "report a problem" submissions.

Backs the public "Report a problem / suggest an update" flow (docs/
API_CONTRACTS.md "Listing reports (`/reports`)", docs/DATA_MODEL.md
"listing_report"). Modeled on `claim_request` (0002) — same submission +
admin-triage shape — but the submitter may be anonymous, so the reporter
columns are nullable and there is no "one pending per brand" partial
unique index.

Purely additive (expand, not contract) — one new table, nothing existing
is altered, matching this project's default migration philosophy (see
0004/0005's headers for the same note).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Content matches
`app/models/listing_report.py` exactly. Revision id kept short
(`alembic_version.version_num` is VARCHAR(32) — see 0002's header).

Revision ID: 0006_listing_report
Revises: 0005_restaurant_brand_website
Create Date: 2026-09-18
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_listing_report"
down_revision: Union[str, None] = "0005_restaurant_brand_website"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "listing_report",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("reporter_email", sa.String(length=254), nullable=True),
        sa.Column("reporter_user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="new",
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["restaurant_brand.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_listing_report_brand_id", "listing_report", ["brand_id"])
    op.create_index(
        "ix_listing_report_reporter_user_id", "listing_report", ["reporter_user_id"]
    )
    # Cheap ordered scan for the admin triage queue and its status filter.
    op.create_index(
        "ix_listing_report_status_submitted",
        "listing_report",
        ["status", "submitted_at"],
    )


def downgrade() -> None:
    op.drop_table("listing_report")
