"""restaurant_brand.deleted_at — nullable soft-delete timestamp.

Backs the admin "Delete listing" action becoming a SOFT delete
(docs/API_CONTRACTS.md "DELETE /restaurants/{id}"): the brand row is kept
(its slug stays reserved, its audit history and follower rows stay intact)
and `deleted_at` is stamped instead. NULL = live. A non-NULL value hides the
brand and every one of its locations from every public / owner / manager
read path; only an admin can still see it, behind an explicit filter, and
restore it (`POST /restaurants/{id}/restore`).

A timestamp rather than a boolean or a status column: `restaurant_brand`
has no status column today (status lives on `restaurant_location`), and a
timestamp also records WHEN it was deleted at no extra cost — same shape as
the existing `claimed_at`.

Purely additive (expand, not contract): one new nullable column, no
backfill, existing rows are live. Hand-authored, not autogenerated (root
CLAUDE.md "NEVER run Alembic migrations — generate migration files only").
Revision id kept short (`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0011_brand_deleted_at
Revises: 0010_merge_0009_heads
Create Date: 2026-09-23
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011_brand_deleted_at"
down_revision: Union[str, None] = "0010_merge_0009_heads"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "restaurant_brand",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("restaurant_brand", "deleted_at")
