"""platform_config — generic admin-configurable key/value table + seed rows
for the two manager/location cap numbers.

See `app/models/platform_config.py`'s module docstring for the full
Postgres-vs-DynamoDB judgment call (a human explicitly asked for
DynamoDB) and PR description for the summary. Short version: this app's
one datastore is Aurora Postgres (root CLAUDE.md); `platform_pricing`
already establishes the "admin-configurable business number lives in a
table, not hardcoded" pattern this reuses; a new DynamoDB table for two
integers would mean new Terraform, new IAM, and a second datastore with
no throughput/latency need to justify it.

Seeds two rows (existing "2" default preserved, not changed):
  max_active_managers_per_location = "2"  (was the hardcoded
    MAX_ACTIVE_MANAGERS_PER_LOCATION_PAID constant in
    location_manager_service.py — see DECISIONS.md "Assignable location
    managers capped at 2 per location on paid tier")
  max_active_locations_per_manager = "2"  (new symmetric cap — see
    DECISIONS.md "Symmetric manager-location cap")
Seeded here (not in a dev-only seed script) because every environment
needs a working default from the moment this table exists.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only").

Revision ID: 0008_platform_config
Revises: 0007_location_about_specialties
Create Date: 2026-09-22
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_platform_config"
down_revision: Union[str, None] = "0007_location_about_specialties"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "platform_config",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )

    platform_config = sa.table(
        "platform_config",
        sa.column("key", sa.String),
        sa.column("value", sa.Text),
    )
    op.bulk_insert(
        platform_config,
        [
            {"key": "max_active_managers_per_location", "value": "2"},
            {"key": "max_active_locations_per_manager", "value": "2"},
        ],
    )


def downgrade() -> None:
    op.drop_table("platform_config")
