"""restaurant_location.slug — each location gets its own public page slug.

Backs the per-location public profile page
`/restaurant/{brand_slug}/{location_slug}` (docs/DECISIONS.md "Location
pages"): hours, deals, menu and address differ per branch, so every location
needs its own readable, stable URL. Unique PER BRAND (`brand_id`, `slug`),
not globally.

Three steps, in one transaction (Postgres DDL is transactional):
  1. add `slug` as NULLABLE;
  2. BACKFILL every existing row with the same deterministic rule the app
     uses for new locations (`app/services/location_slug.py`):
       city slug -> city + street -> + "-2", "-3"...
     processed in (brand_id, id) order, so within a brand the LOWEST id in a
     city gets the plain city slug and later ones get the street form;
  3. set NOT NULL and create the unique constraint.

The backfill logic below is a deliberate COPY of `location_slug.py` — a
migration must be self-contained and must not import app code that can later
drift (changing the app helper would silently change what this migration
does on a fresh database). `tests/unit/test_location_slug.py` loads this
module and asserts both copies produce identical slugs; keep them in sync.

Expect on the real database: every location gets a slug; most brands have one
location, so most slugs are just the city (`irving`). The backfill only
writes rows whose slug is still NULL.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Revision id kept short
(`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0014_location_slug
Revises: 0013_menu
Create Date: 2026-09-24
"""
import re
import unicodedata
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014_location_slug"
down_revision: Union[str, None] = "0013_menu"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT_NAME = "uq_restaurant_location_brand_slug"

# --- Frozen copy of app/services/location_slug.py (see module docstring) ---
MAX_SLUG_LENGTH = 100
RESERVED_LOCATION_SLUGS = frozenset(
    {"report", "reports", "new", "edit", "admin", "api", "menu", "deals", "locations", "location"}
)
_STREET_SUFFIXES = frozenset(
    {
        "st", "street", "ave", "avenue", "blvd", "boulevard", "rd", "road",
        "dr", "drive", "ln", "lane", "ct", "court", "pkwy", "parkway",
        "hwy", "highway", "way", "pl", "place", "cir", "circle", "trl",
        "trail", "ter", "terrace", "fwy", "freeway", "expy", "expressway",
    }
)


def _slugify(text: str) -> str:
    folded = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "-", folded.lower()).strip("-")


def _clip(slug: str, limit: int = MAX_SLUG_LENGTH) -> str:
    return slug[:limit].strip("-")


def _street_part(address_line1: str) -> str:
    first_segment = re.split(r"[,#]", address_line1, maxsplit=1)[0]
    tokens = _slugify(first_segment).split("-") if _slugify(first_segment) else []
    if len(tokens) >= 3 and tokens[-1] in _STREET_SUFFIXES:
        tokens = tokens[:-1]
    return "-".join(tokens)


def pick_location_slug(city: str, address_line1: str, taken) -> str:
    taken_set = set(taken)

    def available(candidate: str) -> bool:
        return candidate not in taken_set and candidate not in RESERVED_LOCATION_SLUGS

    city_slug = _clip(_slugify(city)) or "branch"
    if available(city_slug):
        return city_slug

    street = _street_part(address_line1)
    detailed = _clip(f"{city_slug}-{street}" if street else city_slug)
    if available(detailed):
        return detailed

    n = 2
    while True:
        suffix = f"-{n}"
        candidate = _clip(detailed, MAX_SLUG_LENGTH - len(suffix)) + suffix
        if available(candidate):
            return candidate
        n += 1


def backfill_slugs(rows) -> dict:
    """`rows`: iterable of (id, brand_id, city, address_line1) already
    ordered by (brand_id, id). Returns {id: slug}. Pure — unit-testable."""
    taken_by_brand: dict = {}
    result: dict = {}
    for location_id, brand_id, city, address_line1 in rows:
        taken = taken_by_brand.setdefault(brand_id, set())
        slug = pick_location_slug(city or "", address_line1 or "", taken)
        taken.add(slug)
        result[location_id] = slug
    return result


def upgrade() -> None:
    op.add_column(
        "restaurant_location",
        sa.Column("slug", sa.String(length=100), nullable=True),
    )

    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT id, brand_id, city, address_line1 FROM restaurant_location "
            "ORDER BY brand_id, id"
        )
    ).fetchall()
    slugs = backfill_slugs([(r[0], r[1], r[2], r[3]) for r in rows])
    update = sa.text("UPDATE restaurant_location SET slug = :slug WHERE id = :id AND slug IS NULL")
    for location_id, slug in slugs.items():
        bind.execute(update, {"slug": slug, "id": location_id})

    op.alter_column("restaurant_location", "slug", existing_type=sa.String(length=100), nullable=False)
    op.create_unique_constraint(CONSTRAINT_NAME, "restaurant_location", ["brand_id", "slug"])


def downgrade() -> None:
    op.drop_constraint(CONSTRAINT_NAME, "restaurant_location", type_="unique")
    op.drop_column("restaurant_location", "slug")
