"""menu_section + menu_item — owner/manager-authored menu for a location.

Two new tables (see `app/models/menu_section.py` / `app/models/menu_item.py`
for the full design rationale):

  menu_section  optional named group ("Appetizers") with its own optional
                description; `location_id` ON DELETE CASCADE.
  menu_item     name, optional description, EITHER a free-text `price` OR an
                ordered JSON list of `sizes` ([{label, price}, ...]),
                optional photo keys; `location_id` ON DELETE CASCADE,
                `section_id` nullable ON DELETE SET NULL (ungrouped items).

Also seeds one `platform_config` row, `menu_item_photos_enabled = "false"`:
the menu-item photo capability is fully built but switched OFF until paid
tiers exist (the human flips it with the `set_platform_flag` management
command, docs/SCRIPTS.md). Seeded here so the flag is visible/discoverable
in the table; the code also treats a missing row as OFF, so tests and
freshly-created databases behave identically.

Purely additive (expand, not contract): two new tables + one config row, no
change to any existing table, no backfill. Hand-authored, not autogenerated
(root CLAUDE.md "NEVER run Alembic migrations — generate migration files
only"). Revision id kept short (`alembic_version.version_num` is
VARCHAR(32)).

Revision ID: 0013_menu
Revises: 0012_user_activity_event
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013_menu"
down_revision: Union[str, None] = "0012_user_activity_event"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "menu_section",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_menu_section_location_order", "menu_section", ["location_id", "display_order"]
    )

    op.create_table(
        "menu_item",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("price", sa.String(length=50), nullable=True),
        sa.Column("sizes", sa.JSON(), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("photo_s3_key", sa.String(length=512), nullable=True),
        sa.Column("photo_thumbnail_s3_key", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["section_id"], ["menu_section.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_menu_item_location_section_order",
        "menu_item",
        ["location_id", "section_id", "display_order"],
    )

    platform_config = sa.table(
        "platform_config",
        sa.column("key", sa.String),
        sa.column("value", sa.Text),
    )
    op.bulk_insert(platform_config, [{"key": "menu_item_photos_enabled", "value": "false"}])


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM platform_config WHERE key = 'menu_item_photos_enabled'"))
    op.drop_index("ix_menu_item_location_section_order", table_name="menu_item")
    op.drop_table("menu_item")
    op.drop_index("ix_menu_section_location_order", table_name="menu_section")
    op.drop_table("menu_section")
