"""user_profile — minimal generic display-name table for `registered_user`/
`manager` roles that have no richer local business record of their own
(see `app/models/user_profile.py` for the full rationale, including why
`owner_account` is left untouched).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Purely additive — one new
table, no backfill, no change to any existing table, matches this
project's default migration philosophy (see 0004/0005/0007's headers for
the same note).

Revision id kept short (`alembic_version.version_num` is VARCHAR(32) — see
0002's header).

ORCHESTRATOR NOTE: authored in parallel with at least one other in-flight
migration off the same `down_revision` (0007) — the manager-caps config
table PR. Expect a multi-head collision at merge time; this file's
`down_revision` is still the correct next-sequential parent and does not
need to change for that — the orchestrator reconciles the two heads with a
merge revision once both land.

Revision ID: 0008_user_profile
Revises: 0007_location_about_specialties
Create Date: 2026-09-22
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_user_profile"
down_revision: Union[str, None] = "0007_location_about_specialties"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_profile",
        sa.Column("cognito_sub", sa.String(length=36), primary_key=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_table("user_profile")
