"""restaurant_brand.website — new nullable column.

Closes the "no website/URL field" gap flagged while building CSV bulk
restaurant import (docs/PROJECT_PLAN.csv "CSV bulk restaurant import").
Placed on `restaurant_brand`, not `restaurant_location` — a restaurant's
website describes the concept as a whole, the same brand-vs-location
rationale `restaurant_cuisine` already uses (see that model's docstring
and docs/DATA_MODEL.md "restaurant_cuisine" judgment call). See
docs/DATA_MODEL.md "restaurant_brand" for the full write-up and
docs/DECISIONS.md "CSV bulk restaurant import" for the CSV-import context
this was added alongside.

Purely additive (expand, not contract) — one new nullable column, no
backfill needed, matches this project's default migration philosophy
(see 0004's own header for the same note).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Content matches the new
`website` column on `app/models/restaurant_brand.py` exactly. Revision id
kept short, same reasoning as 0002/0003/0004's own headers
(`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0005_restaurant_brand_website
Revises: 0004_data_deletion_request
Create Date: 2026-09-17
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005_restaurant_brand_website"
down_revision: Union[str, None] = "0004_data_deletion_request"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "restaurant_brand",
        sa.Column("website", sa.String(length=500), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("restaurant_brand", "website")
