"""restaurant_location.about + restaurant_location.specialties — two new
nullable columns.

Backs the owner/manager-editable "About this restaurant / we specialize
in ..." section on the public restaurant page (docs/API_CONTRACTS.md
"PATCH /locations/{id}", docs/DATA_MODEL.md "restaurant_location").
Placed on `restaurant_location`, not `restaurant_brand`, so an assigned
manager can edit them (root CLAUDE.md "Permission model" — managers only
write location-level fields; brand `description` is owner/admin only).

`about` is Text (max 1000 chars enforced by the API schema, not the DB);
`specialties` is a JSON list of short strings (max 8 items, each 1-40
chars, normalised by the API schema). Plain `JSON`, not JSONB, so the
SQLite-backed test suite can create the same column.

Purely additive (expand, not contract) — two new nullable columns, no
backfill needed, matches this project's default migration philosophy
(see 0004/0005's headers for the same note).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Content matches the new
columns on `app/models/restaurant_location.py` exactly. Revision id kept
short (`alembic_version.version_num` is VARCHAR(32) — see 0002's header).

Revision ID: 0007_location_about_specialties
Revises: 0006_listing_report
Create Date: 2026-09-19
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007_location_about_specialties"
down_revision: Union[str, None] = "0006_listing_report"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("restaurant_location", sa.Column("about", sa.Text(), nullable=True))
    op.add_column("restaurant_location", sa.Column("specialties", sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column("restaurant_location", "specialties")
    op.drop_column("restaurant_location", "about")
