"""deal — new table backing the deals engine (Phase 2 feature, explicitly
authorized mid-Phase-1 by the human 2026-09-23; see
docs/DECISIONS.md "Deals: Phase 2 scope explicitly authorized mid-Phase-1").

Content matches app/models/deal.py exactly — see that module's docstring
for the full field-by-field design rationale (deal_type vs applicable_days
as two independent axes, plain JSON for applicable_days so the SQLite test
DB works, ON DELETE CASCADE, no created_by/updated_by columns since
audit_log is the system of record).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only").

Revision ID: 0009_deal
Revises: 0008_location_status_lifecycle
Create Date: 2026-09-23
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009_deal"
down_revision: Union[str, tuple[str, ...], None] = "0008_location_status_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "deal",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "deal_type", sa.String(length=16), server_default="deal", nullable=False
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("applicable_days", sa.JSON(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deal_location_id", "deal", ["location_id"])
    op.create_index("ix_deal_active_end_at", "deal", ["is_active", "end_at"])


def downgrade() -> None:
    op.drop_index("ix_deal_active_end_at", table_name="deal")
    op.drop_index("ix_deal_location_id", table_name="deal")
    op.drop_table("deal")
