"""Visibility switches for the menu and deals (hide without deleting).

Four additive boolean columns, all NOT NULL with a `false` server default so
every existing row stays visible with no backfill:

  menu_item.is_hidden            hide one dish (e.g. sold out)
  menu_section.is_hidden         hide a whole group and its items
  restaurant_location.menu_hidden   hide the entire menu for the location
  restaurant_location.deals_hidden  hide every deal surface for the location
                                    (the per-deal `deal.is_active` toggle
                                    already exists and is unchanged)

Purely additive (expand, not contract). Hand-authored, not autogenerated
(root CLAUDE.md "NEVER run Alembic migrations — generate migration files
only"). Revision id kept short (`alembic_version.version_num` is
VARCHAR(32)).

Revision ID: 0015_hide_menu_and_deals
Revises: 0013_menu
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0015_hide_menu_and_deals"
down_revision: Union[str, None] = "0014_location_slug"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    for table, column in (
        ("menu_item", "is_hidden"),
        ("menu_section", "is_hidden"),
        ("restaurant_location", "menu_hidden"),
        ("restaurant_location", "deals_hidden"),
    ):
        op.add_column(
            table,
            sa.Column(column, sa.Boolean(), server_default="false", nullable=False),
        )


def downgrade() -> None:
    op.drop_column("restaurant_location", "deals_hidden")
    op.drop_column("restaurant_location", "menu_hidden")
    op.drop_column("menu_section", "is_hidden")
    op.drop_column("menu_item", "is_hidden")
