"""location_cuisine — cuisine/dietary tags move from the brand to the location.

Branches of one restaurant differ (a vegetarian branch, a nut-free kitchen,
one branch that does not serve breakfast), so tags are now PER LOCATION
(docs/DECISIONS.md "Cuisine/dietary tags are per location").

Upgrade, in one transaction:
  1. create `location_cuisine` (composite PK `location_id`, `cuisine_tag_id`;
     both FKs `ON DELETE CASCADE`; an index on `cuisine_tag_id` for the
     tag -> locations direction `GET /search` filters on);
  2. BACKFILL it from the brand-level `restaurant_cuisine`: every existing
     location (every status, every brand including soft-deleted ones) gets
     its brand's tags. Self-contained SQL below (`BACKFILL_SQL`), idempotent
     (`ON CONFLICT DO NOTHING`), so re-running it changes nothing.

`restaurant_cuisine` is deliberately LEFT IN PLACE (expand, not contract):
no application code reads or writes it after this migration, but keeping it
makes the migration safely reversible and lets an app rollback still find its
data. It will be dropped by a later migration once the rollout has soaked.

Downgrade drops `location_cuisine` only, after first copying the UNION of each
brand's locations' tags back into `restaurant_cuisine` (`ON CONFLICT DO
NOTHING`) so tags edited or added per location after the upgrade are not lost
to a rollback. Per-location differences necessarily collapse back to the
brand level.

Expect on the real database: `location_cuisine` gets exactly
(number of brand tag links x number of that brand's locations) rows — most
brands have one location, so it is roughly the old `restaurant_cuisine` row
count.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Revision id kept short
(`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0016_location_cuisine
Revises: 0015_hide_menu_and_deals
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0016_location_cuisine"
down_revision: Union[str, None] = "0015_hide_menu_and_deals"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Comma-join (no JOIN ... ON) on purpose: `INSERT ... SELECT ... JOIN ... ON
# ... ON CONFLICT` has a parsing ambiguity in SQLite, and the unit test
# (tests/unit/test_location_cuisine_migration.py) runs this exact text there.
# Plain Postgres accepts it identically.
BACKFILL_SQL = """
INSERT INTO location_cuisine (location_id, cuisine_tag_id)
SELECT l.id, rc.cuisine_tag_id
FROM restaurant_location l, restaurant_cuisine rc
WHERE rc.brand_id = l.brand_id
ON CONFLICT (location_id, cuisine_tag_id) DO NOTHING
"""

# Downgrade: fold the per-location tags back into the brand-level table.
RESTORE_BRAND_LEVEL_SQL = """
INSERT INTO restaurant_cuisine (brand_id, cuisine_tag_id)
SELECT DISTINCT l.brand_id, lc.cuisine_tag_id
FROM location_cuisine lc, restaurant_location l
WHERE l.id = lc.location_id
ON CONFLICT (brand_id, cuisine_tag_id) DO NOTHING
"""


def upgrade() -> None:
    op.create_table(
        "location_cuisine",
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("cuisine_tag_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["cuisine_tag_id"], ["cuisine_tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("location_id", "cuisine_tag_id"),
    )
    op.create_index(
        "ix_location_cuisine_cuisine_tag_id", "location_cuisine", ["cuisine_tag_id"]
    )
    op.execute(sa.text(BACKFILL_SQL))


def downgrade() -> None:
    op.execute(sa.text(RESTORE_BRAND_LEVEL_SQL))
    op.drop_index("ix_location_cuisine_cuisine_tag_id", table_name="location_cuisine")
    op.drop_table("location_cuisine")
