"""restaurant_location status lifecycle + location_reopen_request.

Backs the location status lifecycle work (docs/DECISIONS.md "Location
status lifecycle", `app/models/restaurant_location.py` module docstring).
Two changes:

1. `restaurant_location.is_active` (boolean) -> `restaurant_location.status`
   (string: `active` | `owner_deactivated` | `coming_soon` |
   `closed_pending_reopen`). Not purely additive like most prior
   migrations in this project (0004/0005/0007's own headers) — this one
   replaces a column, so it backfills before dropping:
     - add `status`, nullable, no default, so the backfill below is
       explicit about every existing row rather than relying on a
       column default to paper over it;
     - backfill `status = 'active'` where `is_active = true`,
       `status = 'owner_deactivated'` where `is_active = false` (this is
       the ONLY status the old boolean could ever have meant — the three
       new "why is it hidden" distinctions did not exist before this
       migration, so there is nothing more specific to backfill to);
     - make `status` NOT NULL with a server default of `'active'` (so a
       concurrent insert mid-migration, if one ever happened outside this
       single-transaction DDL, still lands valid);
     - drop `is_active`. `app/models/restaurant_location.py` keeps
       `is_active` alive as a Python-level `hybrid_property` derived from
       `status` — no application code that reads/writes `is_active` needs
       to change, only the stored column moves.

2. `location_reopen_request` — new table, same shape/index pattern as
   `claim_request` (0002): a submission row plus admin approve/reject, with
   a partial unique index enforcing at most one *pending* request per
   location. See `app/models/location_reopen_request.py` for the full
   field-by-field rationale.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Content matches
`app/models/restaurant_location.py` and
`app/models/location_reopen_request.py` exactly. Revision id kept short
(`alembic_version.version_num` is VARCHAR(32) — see 0002's header).

NOTE (multi-head heads-up, per this task's own instructions): another
agent in this same wave may also add a migration off `0007_location_about_
specialties` — if so this becomes a second head and the orchestrator
reconciles the merge order/rebases the `down_revision` chain before both
land on `main`. Nothing in this file assumes it is the only migration
stacked on 0007.

Revision ID: 0008_location_status_lifecycle
Revises: 0007_location_about_specialties
Create Date: 2026-09-22
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_location_status_lifecycle"
down_revision: Union[str, None] = "0007_location_about_specialties"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STATUS_ACTIVE = "active"
_STATUS_OWNER_DEACTIVATED = "owner_deactivated"


def upgrade() -> None:
    # --- restaurant_location.is_active -> restaurant_location.status ----
    op.add_column(
        "restaurant_location",
        sa.Column("status", sa.String(length=24), nullable=True),
    )

    restaurant_location = sa.table(
        "restaurant_location",
        sa.column("status", sa.String(length=24)),
        sa.column("is_active", sa.Boolean()),
    )
    op.execute(
        restaurant_location.update()
        .where(restaurant_location.c.is_active.is_(True))
        .values(status=_STATUS_ACTIVE)
    )
    op.execute(
        restaurant_location.update()
        .where(restaurant_location.c.is_active.is_(False))
        .values(status=_STATUS_OWNER_DEACTIVATED)
    )

    op.alter_column(
        "restaurant_location",
        "status",
        existing_type=sa.String(length=24),
        nullable=False,
        server_default=_STATUS_ACTIVE,
    )
    op.create_index(
        "ix_restaurant_location_status", "restaurant_location", ["status"]
    )
    op.drop_column("restaurant_location", "is_active")

    # --- location_reopen_request -----------------------------------------
    op.create_table(
        "location_reopen_request",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="pending_review",
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["restaurant_location.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_location_reopen_request_location_id",
        "location_reopen_request",
        ["location_id"],
    )
    op.create_index(
        "ix_location_reopen_request_requested_by_user_id",
        "location_reopen_request",
        ["requested_by_user_id"],
    )
    op.create_index(
        "ix_location_reopen_request_status_submitted",
        "location_reopen_request",
        ["status", "submitted_at"],
    )
    op.create_index(
        "uq_location_reopen_request_pending_location",
        "location_reopen_request",
        ["location_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending_review'"),
    )


def downgrade() -> None:
    op.drop_table("location_reopen_request")

    op.add_column(
        "restaurant_location",
        sa.Column("is_active", sa.Boolean(), nullable=True),
    )
    restaurant_location = sa.table(
        "restaurant_location",
        sa.column("status", sa.String(length=24)),
        sa.column("is_active", sa.Boolean()),
    )
    op.execute(
        restaurant_location.update()
        .where(restaurant_location.c.status == _STATUS_ACTIVE)
        .values(is_active=True)
    )
    op.execute(
        restaurant_location.update()
        .where(restaurant_location.c.status != _STATUS_ACTIVE)
        .values(is_active=False)
    )
    op.alter_column(
        "restaurant_location",
        "is_active",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text("true"),
    )
    op.drop_index("ix_restaurant_location_status", table_name="restaurant_location")
    op.drop_column("restaurant_location", "status")
