"""user_profile.city / user_profile.postal_code — a diner's home location.

City and ZIP are mandatory for `registered_user` accounts (user decision
2026-10-07: "mandatory zip/city for registered users"; used to find
restaurants and deals near them). They live on `user_profile`, not Cognito
custom attributes (no Terraform change, immediate read-your-write — same
rationale as `full_name`, see `app/models/user_profile.py`).

Both columns are NULLABLE at the database level on purpose: every existing
diner already has a row (or no row at all) without a location. "Mandatory"
is enforced at signup (frontend) and on `PATCH /auth/me` (a registered_user
location write requires both fields, validated), and EXISTING diners are
nudged with a non-blocking banner until they fill it in — browsing is never
hard-blocked. No backfill.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Purely additive.

Revision ID: 0018_user_profile_location
Revises: 0017_admin_message
Create Date: 2026-10-07
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018_user_profile_location"
down_revision: Union[str, None] = "0017_admin_message"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("user_profile", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("user_profile", sa.Column("postal_code", sa.String(length=10), nullable=True))


def downgrade() -> None:
    op.drop_column("user_profile", "postal_code")
    op.drop_column("user_profile", "city")
