"""Adds `restaurant_photo.thumbnail_s3_key` — S3 image resize pipeline's
thumbnail variant (added 2026-09-16, user request beyond BRD 5.3's
documented single-processed-image spec; see docs/DECISIONS.md "Resize
Lambda: thumbnail variant").

Purely additive (expand, not contract — matches this project's default
migration philosophy, see docs/DECISIONS.md "Terraform environment
promotion" / migration-before-image sequencing): one nullable column added
to the existing `restaurant_photo` table from
`20260912_0002_photo_gallery_and_claim_schema.py`. Nullable because no
backfill is possible or needed — the table has no rows in any real
environment yet (docs/STATUS.md: "no seed data exists anywhere yet"), and
even if it did, existing rows simply have no thumbnail until re-uploaded;
every new row from this point on always gets one (see
app/models/restaurant_photo.py's column comment).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Revision id kept short —
see 0002's own header for why (`alembic_version.version_num` is
VARCHAR(32); 0002's original 36-char id overflowed it and had to be
renamed).

Revision ID: 0003_photo_thumbnail_key
Revises: 0002_photo_gallery_claim_schema
Create Date: 2026-09-16
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_photo_thumbnail_key"
down_revision: Union[str, None] = "0002_photo_gallery_claim_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "restaurant_photo",
        sa.Column("thumbnail_s3_key", sa.String(length=512), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("restaurant_photo", "thumbnail_s3_key")
