"""CCPA data export/deletion follow-up — `data_deletion_request` table +
`owner_account.personal_data_deleted_at` column.

Closes the tracked Phase 1 gap in `docs/PROJECT_PLAN.csv` ("CCPA data
export / deletion flow"). See `docs/DECISIONS.md` "CCPA data
export/deletion" for the full reasoning (admin-reviewed deletion queue
modeled on `claim_request`, synchronous export with no new async/email
infra, audit_log retained not redacted, owner_account anonymized in place
rather than hard-deleted).

Purely additive (expand, not contract — this project's default migration
philosophy, see DECISIONS.md "Terraform environment promotion"): one new
table, one new nullable column on an existing table. No backfill needed —
`personal_data_deleted_at` is NULL for every existing row (nobody has had
a CCPA deletion executed yet).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Content matches
`app/models/data_deletion_request.py` and the new column on
`app/models/owner_account.py` exactly — see `docs/DATA_MODEL.md` for the
column-by-column rationale. Revision id kept short, same reasoning as
0002/0003's own headers (`alembic_version.version_num` is VARCHAR(32)).

Revision ID: 0004_data_deletion_request
Revises: 0003_photo_thumbnail_key
Create Date: 2026-09-16
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004_data_deletion_request"
down_revision: Union[str, None] = "0003_photo_thumbnail_key"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- owner_account: CCPA redaction marker -----------------------------
    op.add_column(
        "owner_account",
        sa.Column("personal_data_deleted_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- data_deletion_request ---------------------------------------------
    op.create_table(
        "data_deletion_request",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("requester_user_id", sa.String(length=36), nullable=False),
        sa.Column("requester_role", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="pending_review",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("data_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_deletion_request_requester_user_id",
        "data_deletion_request",
        ["requester_user_id"],
    )
    # Cheap ordered scan for the single admin review queue.
    op.create_index(
        "ix_data_deletion_request_status_submitted",
        "data_deletion_request",
        ["status", "submitted_at"],
    )
    # Partial unique: at most one pending deletion request per identity.
    op.create_index(
        "uq_data_deletion_request_pending_user",
        "data_deletion_request",
        ["requester_user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending_review'"),
    )


def downgrade() -> None:
    op.drop_table("data_deletion_request")
    op.drop_column("owner_account", "personal_data_deleted_at")
