"""user_activity_event — registered-user search + restaurant-tile-click
history (docs/DECISIONS.md "Registered-user activity tracking (searches +
tile clicks)"). See `app/models/user_activity_event.py` for the full
rationale and the retention rule (12 months, enforced in
`app/services/activity_service.py` — no infra/scheduler involved).

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Purely additive: one new
table, no changes to existing tables, no backfill.

Revision id kept short (`alembic_version.version_num` is VARCHAR(32) —
see 0002's header).

Revision ID: 0011_user_activity_event
Revises: 0010_merge_0009_heads
Create Date: 2026-09-23
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011_user_activity_event"
down_revision: Union[str, None] = "0010_merge_0009_heads"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_activity_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_sub", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_activity_event_user_created",
        "user_activity_event",
        ["user_sub", "created_at"],
    )
    op.create_index(
        "ix_user_activity_event_created", "user_activity_event", ["created_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_user_activity_event_created", table_name="user_activity_event")
    op.drop_index("ix_user_activity_event_user_created", table_name="user_activity_event")
    op.drop_table("user_activity_event")
