"""user_profile.last_seen_at — throttled activity timestamp backing the
admin "Registered users" report (docs/PROJECT_PLAN.csv, docs/DECISIONS.md
"Registered-user last-seen tracking"). See `app/models/user_profile.py`'s
module docstring for the full rationale, and
`app/dependencies/auth.py`/`app/services/auth_service.py::touch_last_seen`
for who writes it and the throttle.

Hand-authored, not autogenerated (root CLAUDE.md "NEVER run Alembic
migrations — generate migration files only"). Purely additive — one
nullable column, no backfill (existing rows simply start `NULL`, read by
the admin report as "never tracked yet" rather than a fabricated "Never
seen" that conflates "existed before this column" with "genuinely never
returned" — see the model docstring).

Revision ID: 0009_user_profile_last_seen_at
Revises: 0008_location_status_lifecycle
Create Date: 2026-09-23
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009_user_profile_last_seen_at"
down_revision: Union[str, None] = "0008_location_status_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "user_profile",
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("user_profile", "last_seen_at")
